[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

; Upload & monitor speed
upload_speed = 921600
monitor_speed = 115200

; Libraries yang dibutuhkan
lib_deps =
  knolleary/PubSubClient @ ^2.8.0
  bblanchon/ArduinoJson  @ ^7.0.0
  ; Uncomment sesuai sensor yang dipakai:
  ; adafruit/DHT sensor library @ ^1.4.6     (untuk DHT22)
  ; paulstoffregen/OneWire @ ^2.3.8           (untuk DS18B20)
  ; milesburton/DallasTemperature @ ^3.11.0   (untuk DS18B20)

; Build flags
build_flags =
  -DCORE_DEBUG_LEVEL=3
