export const Colors = {
  primary:      '#1B5E37',
  primaryLight: '#2E7D52',
  primaryDark:  '#0F3D22',
  primaryBg:    '#E8F5ED',
  accent:       '#22C55E',
  accentLight:  '#DCFCE7',
  success:      '#22C55E',
  successBg:    '#DCFCE7',
  warning:      '#F59E0B',
  warningBg:    '#FEF3C7',
  danger:       '#EF4444',
  dangerBg:     '#FEE2E2',
  info:         '#3B82F6',
  infoBg:       '#DBEAFE',
  white:        '#FFFFFF',
  bgPage:       '#F2F4F3',
  bgCard:       '#FFFFFF',
  border:       '#E5E7EB',
  borderLight:  '#F3F4F6',
  textPrimary:  '#111827',
  textSecondary:'#6B7280',
  textMuted:    '#9CA3AF',
  textWhite:    '#FFFFFF',
  textGreen:    '#1B5E37',
};
